database:
  host: "localhost"
  port: # no port means use default port
  database: "Minecraft"
  user: "root"
  pass: ""
  tableprefix: ""

enabledfeatures:

security:
  user: "commonPlugin"
  pass: "ItIsVeryAdvisableToChangeThisPassword" # Well, what the password says...

synchronizer:
  list:
    - localhost:8743

enabledfeatures:
  list: true

chat:
  enabled: true
  format:
    #  Format parameters:
    #    $1 = playername
    #    $2 = prefix
    #    $3 = suffix
    #    $4 = world name
    #    $5 = highest player group
    #    $6 = mesage

    public: "&f[&9$4&f][&9$5&f][&9$2$1$3&f]: $6"
    admins: "&c[adminchat][$1&c]: $6"
    join: "&ePlayer $1 joined the game in world $4"
    leave: "&ePlayer $1 left the game from world $4"

adminchat:
  admingroup: Admins

permissions:
  enabled: true

